# Generated by Django 4.1.13 on 2024-05-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
