# Generated by Django 4.1.13 on 2024-05-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_profile_image_base64_user_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookedEvents',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='hostedEvents',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='tickets',
            field=models.JSONField(default=dict),
        ),
    ]
