# Generated by Django 4.1.13 on 2024-05-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_bookedevents_user_hostedevents_user_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.JSONField(default=list),
        ),
    ]
