# Generated by Django 4.1.13 on 2024-05-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.JSONField(default=list),
        ),
    ]
